# This is a basic workflow to help you get started with Actions

name: CI build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: 
      - '*'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Publish binaries
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          target: x86_64-unknown-linux-gnu
          override: true
      
      - name: Build
        run: cargo build --all --release && strip target/release/sc && mv target/release/sc target/release/sc_x86_64-unknown-linux-gnu

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/sc_x86_64-unknown-linux-gnu
          asset_name: sc_x86_64-unknown-linux-gnu
          tag: ${{ github.ref }}
          overwrite: true
          body: "Latest binary"
          
